### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by no-defun-allowed** [WillSewell/gc-latency-experiment#28]
I'm looking to use the Common Lisp version of the benchmark in a paper, detailing a parallel non-moving GC for SBCL. There wouldn't appear to be any licenses in this repository; would you be willing to add one please?

(cc: @q3cpma who wrote the CL code.)

**Comment by q3cpma** [comment]
On Sat Feb 4, 2023 at 10:14 AM CET, Hayley Patton wrote:
> I'm looking to use the Common Lisp version of the benchmark in a paper, detailing a parallel GC non-moving for SBCL. There wouldn't appear to be any licenses in this repository; would you be willing to add one please?
Now that's cool!

> (cc: @q3cpma who wrote the CL code.)
For my part, I'm okay with any license for this kind of small potatoes (and with-gensyms doesn't come from me =)); something like MIT, for example.

**Comment by no-defun-allowed** [comment]
Thanks!

**Comment by WillSewell** [comment]
Sounds interesting! Please share the paper once it's done :)

I MIT licensed the repo here: https://github.com/WillSewell/gc-latency-experiment/commit/bff6ea588c201ffd10fd2878509c09b6cdfa9681

**Comment by no-defun-allowed** [comment]
> Sounds interesting! Please share the paper once it's done :)

Thanks, here it is: https://applied-langua.ge/~hayley/swcl-gc.pdf

**Comment by q3cpma** [comment]
On Sun Apr 30, 2023 at 8:03 AM CEST, Hayley Patton wrote:
> > Sounds interesting! Please share the paper once it's done :)
>
> Thanks, here it is: https://applied-langua.ge/~hayley/swcl-gc.pdf
>
> --
> Reply to this email directly or view it on GitHub:
> https://github.com/WillSewell/gc-latency-experiment/issues/28#issuecomment-1528947003
> You are receiving this because you were mentioned.
>
> Message ID: ***@***.***>

Thanks, I saw the talk on ELS and this seems quite promising.

**Comment by WillSewell** [comment]
Amazing. Thanks for sharing!
